version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - run:
          name: 'install dependencies'
          command: npm install
      - run:
          name: 'run frontend tests'
          command: npm run test
      # - run:
      #     name: 'cd into backend'
      #     command: pwd
      #     working_directory: /backend
      # - run:
      #     name: 'run backend tests'
      #     command: npm run test

workflows:
  build_and_test:
    jobs:
      - test
