version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - run:
          name: 'install dependencies'
          command: npm install
      - run:
          name: 'run tests'
          command: npm run test
#   test:
#     docker:
#       - image: circleci/node:14.15.4
#     steps:
#       - checkout
#       - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test


# version: 2.1

# # Define the jobs we want to run for this project
# jobs:
#   run_tests:
#     docker:
#       - image: circleci/node:14.15.4
#     # working_directory: ~/client
#     steps:
#       - checkout
#       - run:
#           name: Install npm dependencies
#           command: |
#             npm install --save
#       - run:
#           name: Run frontend tests
#           command: |
#             ./client/
#       - npm install
#       - npm test


